# Generated by Django 5.1.5 on 2025-01-17 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basin',
            name='curve_number',
            field=models.IntegerField(default=75),
        ),
    ]
