# Generated by Django 5.1.5 on 2025-01-17 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basins', '0004_basin_runoff_coefficient'),
    ]

    operations = [
        migrations.AddField(
            model_name='basin',
            name='P_3_10',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BasinAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precipitation', models.FloatField()),
                ('return_period', models.IntegerField()),
                ('method', models.CharField(choices=[('kirpich', 'Kirpich'), ('uruguay', 'Uruguay')], max_length=50)),
                ('runoff', models.FloatField()),
                ('tc', models.FloatField()),
                ('basin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='basins.basin')),
            ],
        ),
    ]
