# Generated by Django 5.1.5 on 2025-01-17 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basins', '0006_surfacetype_coverage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('min_coefficient', models.FloatField()),
                ('avg_coefficient', models.FloatField()),
                ('max_coefficient', models.FloatField()),
            ],
        ),
    ]
